package com.practice.springcrud.Entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

/*
 * Creating entity class for an employee
 * Going to be an entity
 * Auto inject getters and setters with Lombok annotation
 * Map it to the database
 * Define the table name
 * Primary key field is Long id, autogenerated, best strategy is sequence with
 * postgres but for small projects identity is okay
 * 
 * The notblank, size are validation annotation which will be paired with
 * @valid in the controller body to force validation checks of the fields
 * 
 * @column annotation has to with the database not saving null values
 * 
 */

@Entity
@Table(name = "employees")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "You must provide a first name")
    @Size(max = 50, message = "First Name must be max 50 characters")
    @Column(nullable = false)
    private String firstName;

    @NotBlank(message = "You must provide a last name")
    @Size(max = 50, message = "Last Name must be max = 50 characters")
    @Column(nullable = false)
    private String lastName;

    @NotBlank(message = "You must provide an email")
    @Email(message = "Provide a valid email format")
    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private double salary;

    @NotBlank(message = "Please provide a phone number")
    @Pattern(regexp = "^(233|0)[0-9]{9}$", message = "Your phone number must start with 233 or 0 and followed by 9 numbers")
    @Column(nullable = false, unique = true)
    private String phoneNumber;
}
