package com.practice.springcrud.Entity;

import jakarta.persistence.*;
import lombok.*;

/*
 * Creating entity class for an employee
 * Going to be an entity
 * Auto inject getters and setters with Lombok annotation
 * Map it to the database
 * Define the table name
 * Primary key field is Long id, autogenerated, best strategy is sequence with
 * postgres but for small projects identity is okay
 * 
 *
 * 
 * @column annotation ensure database 
 * instead of using @Data which imports all methods in Objects
 * 
 * Better to use type wrappers than primitives for types in database entities
 * because they can be null but primitives always have a value, which does not
 * refer database reality
 * 
 */

@Entity
@Table(name = "employees")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String firstName;

    @Column(nullable = false)
    private String lastName;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private Double salary;

    @Column(nullable = false, unique = true)
    private String phoneNumber;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private EmployeeStatus status = EmployeeStatus.ACTIVE;
}
