spring.application.name=springcrud

server.port=8082

spring.datasource.url=jdbc:postgres//localhost:5432/springcrud
spring.datasource.username=postgres
spring.datasource.password={insert your password}

spring.jpa.properties.hibernate.dialect=org.hibernate.PostgresSQLDialect
spring.jpa.hibernate.ddl-auto=update